// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: marketplace.capnp

#include "marketplace.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<127> b_a527d407b23a9615 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     21, 150,  58, 178,   7, 212,  39, 165,
     18,   0,   0,   0,   1,   0,   3,   0,
     17, 122, 139, 141,  76,  78,  58, 159,
      3,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     22,   0,   0,   0, 181,   0,   0,   0,
     21,   0,   0,   0, 210,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0, 143,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 114, 107, 101, 116, 112, 108,
     97,  99, 101,  46,  99,  97, 112, 110,
    112,  58,  80, 114, 111, 100, 117,  99,
    116,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     28,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    181,   0,   0,   0,  26,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    176,   0,   0,   0,   3,   0,   1,   0,
    188,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    185,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    184,   0,   0,   0,   3,   0,   1,   0,
    196,   0,   0,   0,   2,   0,   1,   0,
      2,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   2,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    193,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    188,   0,   0,   0,   3,   0,   1,   0,
    200,   0,   0,   0,   2,   0,   1,   0,
      3,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   3,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    197,   0,   0,   0,  98,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    196,   0,   0,   0,   3,   0,   1,   0,
    208,   0,   0,   0,   2,   0,   1,   0,
      4,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   4,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    205,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    200,   0,   0,   0,   3,   0,   1,   0,
    212,   0,   0,   0,   2,   0,   1,   0,
      5,   0,   0,   0,   2,   0,   0,   0,
      0,   0,   1,   0,   5,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    209,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    208,   0,   0,   0,   3,   0,   1,   0,
    220,   0,   0,   0,   2,   0,   1,   0,
      6,   0,   0,   0, 128,   0,   0,   0,
      0,   0,   1,   0,   6,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    217,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    212,   0,   0,   0,   3,   0,   1,   0,
    224,   0,   0,   0,   2,   0,   1,   0,
    105, 100,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    115, 101, 108, 108, 101, 114,  73, 100,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116, 105, 116, 108, 101,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100, 101, 115,  99, 114, 105, 112, 116,
    105, 111, 110,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 114, 105,  99, 101,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99,  97, 116, 101, 103, 111, 114, 121,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    115, 111, 108, 100,   0,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_a527d407b23a9615 = b_a527d407b23a9615.words;
#if !CAPNP_LITE
static const uint16_t m_a527d407b23a9615[] = {5, 3, 0, 4, 1, 6, 2};
static const uint16_t i_a527d407b23a9615[] = {0, 1, 2, 3, 4, 5, 6};
const ::capnp::_::RawSchema s_a527d407b23a9615 = {
  0xa527d407b23a9615, b_a527d407b23a9615.words, 127, nullptr, m_a527d407b23a9615,
  0, 7, i_a527d407b23a9615, nullptr, nullptr, { &s_a527d407b23a9615, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<53> b_c4eaa3a775f92451 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     81,  36, 249, 117, 167, 163, 234, 196,
     18,   0,   0,   0,   3,   0,   0,   0,
     17, 122, 139, 141,  76,  78,  58, 159,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    183,   0,   0,   0, 243,   1,   0,   0,
     21,   0,   0,   0, 242,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0, 199,   0,   0,   0,
    161,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 114, 107, 101, 116, 112, 108,
     97,  99, 101,  46,  99,  97, 112, 110,
    112,  58,  77,  97, 114, 107, 101, 116,
    112, 108,  97,  99, 101,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     12,   0,   0,   0,   3,   0,   5,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    249, 150, 238,  80, 102, 187, 223, 160,
    233,  96, 226,  92, 168,  16, 149, 166,
     81,   0,   0,   0, 114,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     73,   0,   0,   0,   7,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
    186,  34, 223, 116,  24, 163, 188, 151,
     54, 108,  46,  48,  53, 154, 182, 143,
     61,   0,   0,   0, 106,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     53,   0,   0,   0,   7,   0,   0,   0,
      2,   0,   0,   0,   0,   0,   0,   0,
    158, 214, 116,  69, 102, 187,   0, 180,
     87, 126,  82, 234, 178,  93,  61, 238,
     41,   0,   0,   0,  90,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
     99, 114, 101,  97, 116, 101,  80, 114,
    111, 100, 117,  99, 116,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    108, 105, 115, 116,  80, 114, 111, 100,
    117,  99, 116, 115,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    109,  97, 114, 107,  65, 115,  83, 111,
    108, 100,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
      0,   0,   0,   0,   1,   0,   1,   0, }
};
::capnp::word const* const bp_c4eaa3a775f92451 = b_c4eaa3a775f92451.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_c4eaa3a775f92451[] = {
  &s_8fb69a35302e6c36,
  &s_97bca31874df22ba,
  &s_a0dfbb6650ee96f9,
  &s_a69510a85ce260e9,
  &s_b400bb664574d69e,
  &s_ee3d5db2ea527e57,
};
static const uint16_t m_c4eaa3a775f92451[] = {0, 1, 2};
const ::capnp::_::RawSchema s_c4eaa3a775f92451 = {
  0xc4eaa3a775f92451, b_c4eaa3a775f92451.words, 53, d_c4eaa3a775f92451, m_c4eaa3a775f92451,
  6, 3, nullptr, nullptr, nullptr, { &s_c4eaa3a775f92451, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<99> b_a0dfbb6650ee96f9 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    249, 150, 238,  80, 102, 187, 223, 160,
     30,   0,   0,   0,   1,   0,   2,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      3,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 154,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0,  31,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 114, 107, 101, 116, 112, 108,
     97,  99, 101,  46,  99,  97, 112, 110,
    112,  58,  77,  97, 114, 107, 101, 116,
    112, 108,  97,  99, 101,  46,  99, 114,
    101,  97, 116, 101,  80, 114, 111, 100,
    117,  99, 116,  36,  80,  97, 114,  97,
    109, 115,   0,   0,   0,   0,   0,   0,
     20,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    125,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    124,   0,   0,   0,   3,   0,   1,   0,
    136,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    133,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    128,   0,   0,   0,   3,   0,   1,   0,
    140,   0,   0,   0,   2,   0,   1,   0,
      2,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   2,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    137,   0,   0,   0,  98,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    136,   0,   0,   0,   3,   0,   1,   0,
    148,   0,   0,   0,   2,   0,   1,   0,
      3,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   3,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    145,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    140,   0,   0,   0,   3,   0,   1,   0,
    152,   0,   0,   0,   2,   0,   1,   0,
      4,   0,   0,   0,   2,   0,   0,   0,
      0,   0,   1,   0,   4,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    149,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    148,   0,   0,   0,   3,   0,   1,   0,
    160,   0,   0,   0,   2,   0,   1,   0,
    115, 101, 108, 108, 101, 114,  73, 100,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116, 105, 116, 108, 101,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100, 101, 115,  99, 114, 105, 112, 116,
    105, 111, 110,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 114, 105,  99, 101,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99,  97, 116, 101, 103, 111, 114, 121,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_a0dfbb6650ee96f9 = b_a0dfbb6650ee96f9.words;
#if !CAPNP_LITE
static const uint16_t m_a0dfbb6650ee96f9[] = {4, 2, 3, 0, 1};
static const uint16_t i_a0dfbb6650ee96f9[] = {0, 1, 2, 3, 4};
const ::capnp::_::RawSchema s_a0dfbb6650ee96f9 = {
  0xa0dfbb6650ee96f9, b_a0dfbb6650ee96f9.words, 99, nullptr, m_a0dfbb6650ee96f9,
  0, 5, i_a0dfbb6650ee96f9, nullptr, nullptr, { &s_a0dfbb6650ee96f9, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<37> b_a69510a85ce260e9 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    233,  96, 226,  92, 168,  16, 149, 166,
     30,   0,   0,   0,   1,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 162,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 114, 107, 101, 116, 112, 108,
     97,  99, 101,  46,  99,  97, 112, 110,
    112,  58,  77,  97, 114, 107, 101, 116,
    112, 108,  97,  99, 101,  46,  99, 114,
    101,  97, 116, 101,  80, 114, 111, 100,
    117,  99, 116,  36,  82, 101, 115, 117,
    108, 116, 115,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  82,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   3,   0,   1,   0,
     24,   0,   0,   0,   2,   0,   1,   0,
    112, 114, 111, 100, 117,  99, 116,  73,
    100,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_a69510a85ce260e9 = b_a69510a85ce260e9.words;
#if !CAPNP_LITE
static const uint16_t m_a69510a85ce260e9[] = {0};
static const uint16_t i_a69510a85ce260e9[] = {0};
const ::capnp::_::RawSchema s_a69510a85ce260e9 = {
  0xa69510a85ce260e9, b_a69510a85ce260e9.words, 37, nullptr, m_a69510a85ce260e9,
  0, 1, i_a69510a85ce260e9, nullptr, nullptr, { &s_a69510a85ce260e9, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<20> b_97bca31874df22ba = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    186,  34, 223, 116,  24, 163, 188, 151,
     30,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 146,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 114, 107, 101, 116, 112, 108,
     97,  99, 101,  46,  99,  97, 112, 110,
    112,  58,  77,  97, 114, 107, 101, 116,
    112, 108,  97,  99, 101,  46, 108, 105,
    115, 116,  80, 114, 111, 100, 117,  99,
    116, 115,  36,  80,  97, 114,  97, 109,
    115,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_97bca31874df22ba = b_97bca31874df22ba.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_97bca31874df22ba = {
  0x97bca31874df22ba, b_97bca31874df22ba.words, 20, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_97bca31874df22ba, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<41> b_8fb69a35302e6c36 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     54, 108,  46,  48,  53, 154, 182, 143,
     30,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 154,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 114, 107, 101, 116, 112, 108,
     97,  99, 101,  46,  99,  97, 112, 110,
    112,  58,  77,  97, 114, 107, 101, 116,
    112, 108,  97,  99, 101,  46, 108, 105,
    115, 116,  80, 114, 111, 100, 117,  99,
    116, 115,  36,  82, 101, 115, 117, 108,
    116, 115,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   3,   0,   1,   0,
     40,   0,   0,   0,   2,   0,   1,   0,
    112, 114, 111, 100, 117,  99, 116, 115,
      0,   0,   0,   0,   0,   0,   0,   0,
     14,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   3,   0,   1,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
     21, 150,  58, 178,   7, 212,  39, 165,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     14,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_8fb69a35302e6c36 = b_8fb69a35302e6c36.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_8fb69a35302e6c36[] = {
  &s_a527d407b23a9615,
};
static const uint16_t m_8fb69a35302e6c36[] = {0};
static const uint16_t i_8fb69a35302e6c36[] = {0};
const ::capnp::_::RawSchema s_8fb69a35302e6c36 = {
  0x8fb69a35302e6c36, b_8fb69a35302e6c36.words, 41, d_8fb69a35302e6c36, m_8fb69a35302e6c36,
  1, 1, i_8fb69a35302e6c36, nullptr, nullptr, { &s_8fb69a35302e6c36, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<36> b_b400bb664574d69e = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    158, 214, 116,  69, 102, 187,   0, 180,
     30,   0,   0,   0,   1,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 130,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 114, 107, 101, 116, 112, 108,
     97,  99, 101,  46,  99,  97, 112, 110,
    112,  58,  77,  97, 114, 107, 101, 116,
    112, 108,  97,  99, 101,  46, 109,  97,
    114, 107,  65, 115,  83, 111, 108, 100,
     36,  80,  97, 114,  97, 109, 115,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  82,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   3,   0,   1,   0,
     24,   0,   0,   0,   2,   0,   1,   0,
    112, 114, 111, 100, 117,  99, 116,  73,
    100,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_b400bb664574d69e = b_b400bb664574d69e.words;
#if !CAPNP_LITE
static const uint16_t m_b400bb664574d69e[] = {0};
static const uint16_t i_b400bb664574d69e[] = {0};
const ::capnp::_::RawSchema s_b400bb664574d69e = {
  0xb400bb664574d69e, b_b400bb664574d69e.words, 36, nullptr, m_b400bb664574d69e,
  0, 1, i_b400bb664574d69e, nullptr, nullptr, { &s_b400bb664574d69e, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<36> b_ee3d5db2ea527e57 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     87, 126,  82, 234, 178,  93,  61, 238,
     30,   0,   0,   0,   1,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 138,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 114, 107, 101, 116, 112, 108,
     97,  99, 101,  46,  99,  97, 112, 110,
    112,  58,  77,  97, 114, 107, 101, 116,
    112, 108,  97,  99, 101,  46, 109,  97,
    114, 107,  65, 115,  83, 111, 108, 100,
     36,  82, 101, 115, 117, 108, 116, 115,
      0,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  66,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    115, 117,  99,  99, 101, 115, 115,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_ee3d5db2ea527e57 = b_ee3d5db2ea527e57.words;
#if !CAPNP_LITE
static const uint16_t m_ee3d5db2ea527e57[] = {0};
static const uint16_t i_ee3d5db2ea527e57[] = {0};
const ::capnp::_::RawSchema s_ee3d5db2ea527e57 = {
  0xee3d5db2ea527e57, b_ee3d5db2ea527e57.words, 36, nullptr, m_ee3d5db2ea527e57,
  0, 1, i_ee3d5db2ea527e57, nullptr, nullptr, { &s_ee3d5db2ea527e57, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


// Product
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Product::_capnpPrivate::dataWordSize;
constexpr uint16_t Product::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Product::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Product::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

#if !CAPNP_LITE
::capnp::Request< ::Marketplace::CreateProductParams,  ::Marketplace::CreateProductResults>
Marketplace::Client::createProductRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::Marketplace::CreateProductParams,  ::Marketplace::CreateProductResults>(
      0xc4eaa3a775f92451ull, 0, sizeHint, {true});
}
::kj::Promise<void> Marketplace::Server::createProduct(CreateProductContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "marketplace.capnp:Marketplace", "createProduct",
      0xc4eaa3a775f92451ull, 0);
}
::capnp::Request< ::Marketplace::ListProductsParams,  ::Marketplace::ListProductsResults>
Marketplace::Client::listProductsRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::Marketplace::ListProductsParams,  ::Marketplace::ListProductsResults>(
      0xc4eaa3a775f92451ull, 1, sizeHint, {true});
}
::kj::Promise<void> Marketplace::Server::listProducts(ListProductsContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "marketplace.capnp:Marketplace", "listProducts",
      0xc4eaa3a775f92451ull, 1);
}
::capnp::Request< ::Marketplace::MarkAsSoldParams,  ::Marketplace::MarkAsSoldResults>
Marketplace::Client::markAsSoldRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::Marketplace::MarkAsSoldParams,  ::Marketplace::MarkAsSoldResults>(
      0xc4eaa3a775f92451ull, 2, sizeHint, {true});
}
::kj::Promise<void> Marketplace::Server::markAsSold(MarkAsSoldContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "marketplace.capnp:Marketplace", "markAsSold",
      0xc4eaa3a775f92451ull, 2);
}
::capnp::Capability::Server::DispatchCallResult Marketplace::Server::dispatchCall(
    uint64_t interfaceId, uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (interfaceId) {
    case 0xc4eaa3a775f92451ull:
      return dispatchCallInternal(methodId, context);
    default:
      return internalUnimplemented("marketplace.capnp:Marketplace", interfaceId);
  }
}
::capnp::Capability::Server::DispatchCallResult Marketplace::Server::dispatchCallInternal(
    uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (methodId) {
    case 0:
      return {
        createProduct(::capnp::Capability::Server::internalGetTypedContext<
             ::Marketplace::CreateProductParams,  ::Marketplace::CreateProductResults>(context)),
        false,
        false
      };
    case 1:
      return {
        listProducts(::capnp::Capability::Server::internalGetTypedContext<
             ::Marketplace::ListProductsParams,  ::Marketplace::ListProductsResults>(context)),
        false,
        false
      };
    case 2:
      return {
        markAsSold(::capnp::Capability::Server::internalGetTypedContext<
             ::Marketplace::MarkAsSoldParams,  ::Marketplace::MarkAsSoldResults>(context)),
        false,
        false
      };
    default:
      (void)context;
      return ::capnp::Capability::Server::internalUnimplemented(
          "marketplace.capnp:Marketplace",
          0xc4eaa3a775f92451ull, methodId);
  }
}
#endif  // !CAPNP_LITE

// Marketplace
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Marketplace::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Marketplace::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Marketplace::CreateProductParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Marketplace::CreateProductParams::_capnpPrivate::dataWordSize;
constexpr uint16_t Marketplace::CreateProductParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Marketplace::CreateProductParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Marketplace::CreateProductParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Marketplace::CreateProductResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Marketplace::CreateProductResults::_capnpPrivate::dataWordSize;
constexpr uint16_t Marketplace::CreateProductResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Marketplace::CreateProductResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Marketplace::CreateProductResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Marketplace::ListProductsParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Marketplace::ListProductsParams::_capnpPrivate::dataWordSize;
constexpr uint16_t Marketplace::ListProductsParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Marketplace::ListProductsParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Marketplace::ListProductsParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Marketplace::ListProductsResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Marketplace::ListProductsResults::_capnpPrivate::dataWordSize;
constexpr uint16_t Marketplace::ListProductsResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Marketplace::ListProductsResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Marketplace::ListProductsResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Marketplace::MarkAsSoldParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Marketplace::MarkAsSoldParams::_capnpPrivate::dataWordSize;
constexpr uint16_t Marketplace::MarkAsSoldParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Marketplace::MarkAsSoldParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Marketplace::MarkAsSoldParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Marketplace::MarkAsSoldResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Marketplace::MarkAsSoldResults::_capnpPrivate::dataWordSize;
constexpr uint16_t Marketplace::MarkAsSoldResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Marketplace::MarkAsSoldResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Marketplace::MarkAsSoldResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE



